on:
  push:
    branches:
      - main

name: Docker Build and Push

jobs:
  # https://zenn.dev/515hikaru/articles/migrate-to-ghcr
  publish_docker_image:
    runs-on: ubuntu-latest
    # https://stackoverflow.com/questions/76607955/error-denied-installation-not-allowed-to-create-organization-package
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/$GITHUB_ACTOR/github-package-publish-example:latest \
          --tag ghcr.io/$GITHUB_ACTOR/github-package-publish-example:$(echo $GITHUB_SHA | head -c7) \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$GITHUB_ACTOR/github-package-publish-example:latest
          docker push ghcr.io/$GITHUB_ACTOR/github-package-publish-example:$(echo $GITHUB_SHA | head -c7)
